import { createSlice } from "@reduxjs/toolkit";

// Define the initial state of the scores slice
const initialState = {
  scoresData: null,
};

// Create the scoreSlice using createSlice function
const scoreSlice = createSlice({
  name: "scores",
  initialState,

  // Reducer functions to handle state updates
  reducers: {
    // Reducer for setting the scoresData in the state
    setScoresData: (state, action) => {
      state.scoresData = action.payload;
    },

    // Reducer for clearing the scoresData from the state
    clearScoresData: (state) => {
      state.scoresData = null;
    },
  },
});

// Extract the action creators from the scoreSlice and export them
export const { setScoresData, clearScoresData } = scoreSlice.actions;
// Export the reducer function generated by the scoreSlice
export default scoreSlice.reducer;
